<script language=JavaScript>
/*  Provided a popup window for registration */
function regpopup(sw) {
  edit = window.open('http://csg.sph.umich.edu/register.php?sw='+sw, 'register',
    'width=600,height=500,resizable,scrollbars,menubar');
}
</script>

<!-- Generate banner at top -->
<div class="banner">
<a href="/index.php"><img align="center" src="/common/logo_20071207.jpg" alt="Center for Statistical Genetics" border="0"/></a>
</div>
<!-- End top banner/logo for page -->
