<!-- Generate page. Menus on left. Page in middle. Possibly menus on right -->
<table summary="2,3 columns">
<tr>  <td valign="top" class="leftcol">

<table cellspacing="1" cellpadding="0" class="menu-top"><tr><td>
  <table cellspacing="0" cellpadding="1" width="100%">
    <tr><td valign="middle" class="menu-hdr">&nbsp;Main</td></tr>
    <tr><td class="menus">
      &nbsp;<a class="menus" href="http://csg.sph.umich.edu">CSG Home</a>
    </td></tr>
  </table>
</td></tr></table><br>
