<table cellspacing="1" cellpadding="0" class="menu-top"><tr><td>
  <table cellspacing="0" cellpadding="1" width="100%">

    <tr><td valign="middle" class="menu-hdr">MotifOrganizer</td></tr>

    <tr><td class="menus">
      &nbsp;<a class="menus" href="index.shtml">Home</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>

    <tr><td class="menus">
      &nbsp;<a class="menus" href="getProg.shtml">Download</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">
      &nbsp;<a class="menus" href="documents.shtml">Documentation</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">&nbsp;Sample Files</td></tr>

    <tr><td class="menus">
      &nbsp;<a class="menus" href="sample.txt">&nbsp;&nbsp;Input Files</a>
    </td></tr>
    <tr><td class="menus">
      &nbsp;<a class="menus" href="output.clean.txt">&nbsp;&nbsp;Output Files</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">
      &nbsp;<a class="menus" href="update.txt">Update &amp; Bug Log</a>
    </td></tr>
    <tr><td class="menus-spacer">&nbsp;-----------------------------------------------</td></tr>
    <tr><td class="menus">
      &nbsp;<a class="menus" href="javascript:regpopup('MOTIF');">Register</a>
    </td></tr>
  </table>
</td></tr></table><br>
